import { Options } from './options-manager'
import { TTS, TTSTypes } from './tts/tts'

export function getOptions() {
    return {
        [sc.OPTION_CATEGORY.ASSISTS]: {
            crossedeyes: {
                autoUpdate: {
                    type: 'CHECKBOX',
                    init: true,
                    saveToLocalStorage: true,
                },
                spacialAudio: {
                    type: 'CHECKBOX',
                    init: true,
                },
                loudWalls: {
                    type: 'CHECKBOX',
                    init: true,
                },
                loudEntities: {
                    type: 'CHECKBOX',
                    init: true,
                },
                hints: {
                    type: 'CHECKBOX',
                    init: true,
                },
                textBeeping: {
                    type: 'CHECKBOX',
                    init: true,
                },
                hudVisible: {
                    type: 'CHECKBOX',
                    init: true,
                    saveToLocalStorage: true,
                },
            },
            battle: {
                enemyVulnerableMulti: {
                    type: 'OBJECT_SLIDER',
                    init: 2,
                    min: 1,
                    max: 5,
                    step: 0.1,
                    fill: true,
                    showPercentage: true,
                },
            },
            tts: {
                tts: {
                    type: 'CHECKBOX',
                    init: true,
                    changeEvent: () => TTS.g.optionChangeEvent(),
                    saveToLocalStorage: true,
                },
                ttsType: {
                    type: 'BUTTON_GROUP',
                    init: TTSTypes['Web Speech'],
                    enum: TTSTypes,
                    changeEvent: () => TTS.g.setup(),
                    saveToLocalStorage: true,
                },
                ttsChar: {
                    type: 'CHECKBOX',
                    init: true,
                },
                ttsSpeed: {
                    type: 'OBJECT_SLIDER',
                    init: 1,
                    min: 0.8,
                    max: 5,
                    step: 0.1,
                    fill: true,
                    showPercentage: true,
                },
                ttsVolume: {
                    type: 'OBJECT_SLIDER',
                    init: 1,
                    min: 0.5,
                    max: 2,
                    step: 0.1,
                    fill: true,
                    showPercentage: true,
                },
                ttsPitch: {
                    type: 'OBJECT_SLIDER',
                    init: 1,
                    min: 0.5,
                    max: 2,
                    step: 0.1,
                    fill: true,
                    showPercentage: true,
                },
            },
            volumes: {
                footstepVolume: {
                    type: 'OBJECT_SLIDER',
                    init: 1.5,
                    min: 1,
                    max: 3,
                    step: 0.1,
                    fill: true,
                    showPercentage: true,
                },
                jumpVolume: {
                    type: 'OBJECT_SLIDER',
                    init: 1.5,
                    min: 1,
                    max: 3,
                    step: 0.1,
                    fill: true,
                    showPercentage: true,
                },
                dashVoulme: {
                    type: 'OBJECT_SLIDER',
                    init: 1.5,
                    min: 1,
                    max: 3,
                    step: 0.1,
                    fill: true,
                    showPercentage: true,
                },
                wallVolume: {
                    type: 'OBJECT_SLIDER',
                    init: 1,
                    min: 0,
                    max: 1.5,
                    step: 0.1,
                    fill: true,
                    showPercentage: true,
                },
                wallBumpVolume: {
                    type: 'OBJECT_SLIDER',
                    init: 1,
                    min: 0,
                    max: 2,
                    step: 0.1,
                    fill: true,
                    showPercentage: true,
                },
                jumpHintsVolume: {
                    type: 'OBJECT_SLIDER',
                    init: 1,
                    min: 0,
                    max: 1.5,
                    step: 0.1,
                    fill: true,
                    showPercentage: true,
                },
                wallScanVolume: {
                    type: 'OBJECT_SLIDER',
                    init: 1,
                    min: 0,
                    max: 1.5,
                    step: 0.1,
                    fill: true,
                    showPercentage: true,
                },
                hintsVolume: {
                    type: 'OBJECT_SLIDER',
                    init: 1,
                    min: 0,
                    max: 1.5,
                    step: 0.1,
                    fill: true,
                    showPercentage: true,
                },
                interactableVolume: {
                    type: 'OBJECT_SLIDER',
                    init: 1,
                    min: 0,
                    max: 3,
                    step: 0.1,
                    fill: true,
                    showPercentage: true,
                },
                entityHintsVolume: {
                    type: 'OBJECT_SLIDER',
                    init: 1,
                    min: 0,
                    max: 2,
                    step: 0.1,
                    fill: true,
                    showPercentage: true,
                },
            },
        },
    } as const satisfies Options
}
