export const expressionMap: Record<string, string> = {
    ANGRY: 'Angry',
    ANGRY_GLASS: 'Angry',
    ANNOYED: 'Annoyed',
    ASKING: 'Asking',
    ASTONISHED: 'Astonished',
    AWAY: '',
    AWAY_PANIC: 'Panicing',
    AWESOME: 'Poggers',
    AWWW: 'To do expreesion dont forget me please a a a a a a a a a', //todo
    BADASS: '',
    BALD: '',
    BLANK: '',
    BORED: 'Bored',
    BORED_AR: 'Bored',
    BRIGHT: 'Happy',
    BROKEN: '',
    CHAIR_BACK: 'Sitting in a chair,',
    CHAIR_DEFAULT: 'Sitting in a chair,',
    CHAIR_DOWN: 'Sitting in a chair,',
    CHAIR_SIDE: 'Sitting in a chair,',
    CHARMED: 'Charmed',
    COMPLAINING: 'Complaining',
    COMPLEX: 'Complex',
    CONCERNED: 'Concerned',
    CONCERNED_GLASS: 'Concerned',
    CONDESCENDING: 'Condescending',
    CONDESCENDING_AR: 'Condescending',
    CONFLICTED: 'Conflicted',
    CONFUSED: 'Confused',
    CONFUSED_AR: 'Confused',
    CONTENT: 'Content',
    CRAZY_GRIN: 'Stressed Smiling',
    CRAZY_GRIN2: 'Stressed Smiling',
    CRAZY_GRIN3: 'Stressed Squinted eyes',
    CRAZY_PANIC: 'Stressed Panicking',
    CRAZY_PANIC2: 'Stressed Panicking',
    CRAZY_SMILE: 'Stressed Smiling',
    CRY: 'Sobbing',
    CULTURE: 'Smiling Closed eyes',
    CURIOUS: 'Curious',
    DARK: '',
    DEAD_INSIDE: 'Dead inside',
    DEAD_INSIDE2: 'Dead inside',
    DEFAULT: '',
    DEFAULT_AR: '',
    DEFAULT_GLASS: '',
    DENYING: 'Denying',
    DESPERATE: 'Desperate',
    DETERMINED: 'Determined',
    DISGUSTED: 'Disgusted',
    DOWN: '',
    DOWN_AR: '',
    DOWN_EYE_CLOSED: '',
    DOWN_GLASS: '',
    DOWN_PANIC: 'Panicking',
    DOWN_SMILE: 'Smiling',
    DOWN_SMILE_GLASS: 'Smiling',
    DOWN_TALK: '',
    DOWN_TALK_AR: '',
    DRAMATIC: 'Dramatic',
    DUMBFOUNDED: 'Dumbfounded',
    EMBARRASSED: 'Embarrassed',
    EVIL_GRIN: 'Closed eyes',
    EXCITED: 'Excited',
    EXHAUSTED: 'Exhausted',
    EYES_CLOSED: 'Closed eyes',
    FROWN: 'Frown',
    FROWN_AR: 'Frown',
    FUNNY_SMILE: 'Funny smile',
    GLASS: '',
    GLASS_ANGRY: 'Angry',
    GLASS_COOL: '',
    GLASS_DEFAULT: '',
    GLASS_GRIN: 'Smiling',
    GLASS_IRRITATED: 'Irritated',
    GLASS_NERVOUS: 'Nervous',
    GLASS_SMILE: 'Smiling',
    GLASS_TOWARD: '',
    GLASS_UP: '',
    GLASS_UP_COOL: '',
    GLASS_UP_GRIN: 'Grinning',
    GLASS_WHISTLING: 'Whistling',
    GRIN: 'Grinning',
    HAND_FIVE: 'Showing five fingers',
    HAND_FOUR: 'Showing four fingers',
    HAND_FOUR_SMUG: 'Showing four fingers, smug',
    HAND_ONE: 'Showing one finger',
    HAND_ONE_THINKING: 'Showing one finger, thinking',
    HAND_ONE_WHISTLING: 'Showing one finger, whistling',
    HAND_POINT: 'Finger pointing',
    HAND_POINT_ANGRY: 'Finger pointing, angry',
    HAND_POINT_DETERMINED: 'Finger pointing, determined',
    HAND_POINT_JOKE: 'Finger pointing, joking',
    HAND_POINT_SELF: 'Finger pointing at self',
    HAND_POINT_SELF_DETERMINED: 'Finger pointing at self, determined',
    HAND_SELF_SURPRISED: 'Finger pointing at self, suprised',
    HAND_THREE: 'Showing three fingers',
    HAND_THREE_SMUG: 'Showing three fingers, smug',
    HAND_THREE_THINKING: 'Showing three fingers, thinking',
    HAND_TWO: 'Showing two fingers',
    HAND_TWO_THINKING: 'Showing two fingers, thinking',
    HAND_WEIRD: 'Trying to curle fingers',
    HAND_WEIRD_DETERMINED: 'Trying to curle finges, determined',
    HAND_WEIRD_THINK: 'Trying to curle finges, thinking',
    HAND_WEIRD_TIRED: 'Trying to curle fingers, tired',
    HAND_WTF: 'Showing impossibly curled fingers',
    HAND_WTF_SURPRISED: 'Showing impossibly curled fingers, suprised',
    HAPPY: 'Happy',
    HOLD: 'Beaing held',
    HOLD_HORNS: 'Holding horns, suprised',
    HOLD_HORNS_ANNOYED: 'Holding horns, very annoyed',
    HOLOGRAM: 'Hologram',
    INNOCENT: 'Innocent',
    INSANE: 'Insane',
    INSANE_DOWN: 'Insane, grinning',
    INTENSE1: 'Intense',
    INTENSE2: 'Intense',
    IRRITATED: 'Irritated',
    JOKING: 'Joking',
    LAUGH: 'Laughing',
    LAUGH_AR: 'Laughing',
    LAUGHING: 'Laughing',
    LAUGHING_DOWN: 'Laughing',
    LECTURING: 'Lecturing',
    MASKED: 'Masked',
    MASKED_DOWN: 'Masked',
    MASKED_DOWN_SMILE: 'Masked, smiling',
    MASKED_FROWN: 'Masked, frown',
    MASKED_GNASH: 'Masked, gnash',
    MASKED_GRIN: 'Masked, grin',
    MASKED_LAUGH: 'Masked, laughing',
    MASKED_SMILE: 'Masked, smiling',
    MASKED_UNPLEASED: 'Masked, unpleased',
    MASKED_WARN: 'Masked, suprised',
    MOPING: 'Moping',
    NERVOUS: 'Nervous',
    NOD: 'Nod',
    NOD_HAPPY: 'Happy nod',
    NOD_HARD1: 'Sad, hard nod',
    NOD_HARD2: 'Sad, hard nod',
    NOD_NERVOUS: 'Nervous nod',
    NOD_SAD: 'Sad nod',
    NODS_DEAD_INSIDE: 'Dead inside nod',
    NORM_SERIOUS: 'Serious',
    NOSTALGIC: 'Nostalgic',
    NOTIFYING: 'Notifying',
    PAIN: 'In pain',
    PAIN_EYE_CLOSED: 'In pain',
    PANIC: 'Panicing',
    PISSED: 'Pissed',
    PLOTTING: 'Plotting',
    PLOTTING_GLASS: 'Plotting',
    POINTING: 'Heroic pointing ',
    PONDERING: 'Pondering',
    PONDERING_NORM: 'Pondering',
    PRE_CRY: 'Tearing up',
    PRE_CRY1: 'Tearing up',
    PRE_CRY2: 'Tearing up',
    PROUD: 'Proud',
    RAGING: 'Raging',
    RANTING: 'Ranting',
    ROAR: 'Yelling',
    ROAR_GLASS: 'Yelling',
    ROLL_EYES: 'Rolling eyes',
    SAD: 'Sad',
    SAD_AWAY: 'Sad',
    SAD_SMILE: 'Sad smile',
    SARCASTIC: 'Sarcastic',
    SCARED: 'Scared',
    SCEPTICAL: 'Sceptical',
    SCEPTICAL_GLASS: 'Sceptical',
    SCOLDING: 'Annoyed',
    SCREAM: 'Screaming',
    SERIOUS: 'Serious',
    SHADOW: 'Shadow',
    SHAKE: 'Shaking head',
    SHAKE_EYE_CLOSED: 'Angry shaking head',
    SHAKE_PANIC: 'Terrified shaking head',
    SHAKE_SAD: 'Sad shaking head',
    SHAKE_SCARED: 'Scared shaking head',
    SHOCK: 'Shocked',
    SHOCKED: 'Shocked',
    SHOUT: 'Shouting',
    SHOUT_AR: 'Shouting',
    SHOUT_GLASS: 'Shouting',
    SHOUTING: 'Shouting',
    SHOUTING2: 'Shouting',
    SHOUT_PANIC: 'Panic shouting',
    SHRUG: 'Shrug',
    SIDE_SMILE: 'Smiling',
    SKEPTICAL: 'Sceptical',
    SLEEP: 'Sleeping',
    SLEEPING: 'Sleeping',
    SMILE: 'Smiling',
    SMILE_AR: 'Smiling',
    SMILE_GLASS: 'Smiling',
    SMUG: 'Smug',
    SNARL: 'Snarling',
    STAR_POINTING: 'Showing star sign',
    STAR_POINTING_DETERMINED: 'Showing star in sign language, determined',
    STAR_POINTING_PRE: 'Trying to show star in sign language',
    STERN: '',
    STERN_GLASS: '',
    STRICT: 'Angry',
    SURPRISED: 'Suprised',
    SURPRISED_AWAY: 'Suprised',
    SURPRISED_TOWARD: 'Suprised',
    SUSPICIOUS: 'Suspicious',
    SWEATY_SMILE: 'Sweaty, smiling',
    TAUNTING: 'Taunting',
    THINKING: 'Thinking',
    THOUGHTFUL: 'Thoughtful',
    THOUGHTFUL_NORM: 'Thoughtful',
    THOUGHTFUL_TOWARD: 'Thoughtful',
    TIRED: 'Tired',
    TOUCHED: 'Touched',
    TOWARD: '',
    TOWARD_AR: '',
    TOWARD_GLASS: '',
    TOWARDS: '',
    TOWARD_TALK: '',
    TOWARD_TALK_AR: '',
    UNCERTAIN: 'Uncertain',
    UNHORNED: '',
    UP: '',
    UP_GRIN: '',
    WAKING: 'Waking up',
    WATCH_OUT_BADASS: '',
    WEIRD_HAND: 'Showing impossibly curled fingers',
    WHISTLING: 'Whistling',
    WHY: '', //todo
    WINK: 'Winking',
    WONDERING: 'Wondering',
    WORRIED: 'Worried',
    WRAP_HEAD: 'Terrified, wraping head',
    WRAP_SHOULDER: 'Terrified, wraping shoulders',
    YELL: 'Yelling',
}
